name: Deploy to NCP (Push-only)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NCR_REGISTRY: ${{ secrets.NCR_REGISTRY }}      # ex) boxbox-container.kr.ncr.ntruss.com
      NCR_NAMESPACE: ${{ secrets.NCR_NAMESPACE }}    # ex) boxbox
      APP_NAME: ${{ secrets.APP_NAME }}              # ex) myapp
      IMAGE: ${{ secrets.NCR_REGISTRY }}/${{ secrets.NCR_NAMESPACE }}/${{ secrets.APP_NAME }}
      TAG: ${{ github.run_number }}-${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
      - run: chmod +x ./gradlew
      - run: ./gradlew clean build

      - uses: docker/setup-buildx-action@v3

      - name: Login to NCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.NCR_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}   # MANAGER 권한
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build & Push
        shell: bash
        run: |
          set -euo pipefail

          clean() {
            local v="$1"
            v="${v//$'\n'/}"; v="${v//$'\r'/}"
            v="${v#http://}"; v="${v#https://}"
            v="${v%/}"; v="${v#/}"
            printf '%s' "$v"
          }

          REG="$(clean "${NCR_REGISTRY:-}")"
          NS="$(clean "${NCR_NAMESPACE:-}")"
          APP="$(clean "${APP_NAME:-}")"

          IMAGE_LC="$(echo "${REG}/${NS}/${APP}" | tr '[:upper:]' '[:lower:]')"

          echo "Repo  : ${IMAGE_LC}"
          echo "Tag   : ${TAG}"

          echo -n "${IMAGE_LC}:${TAG}" | od -An -t x1

          docker build -t "${IMAGE_LC}:${TAG}" -t "${IMAGE_LC}:latest" .
          docker push "${IMAGE_LC}:${TAG}"
          docker push "${IMAGE_LC}:latest"