name: Deploy to NCP (Push-only)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NCR_REGISTRY: ${{ secrets.NCR_REGISTRY }}      # ex) boxbox-container.kr.ncr.ntruss.com
      NCR_NAMESPACE: ${{ secrets.NCR_NAMESPACE }}    # ex) boxbox
      APP_NAME: ${{ secrets.APP_NAME }}              # ex) myapp
      IMAGE: ${{ secrets.NCR_REGISTRY }}/${{ secrets.NCR_NAMESPACE }}/${{ secrets.APP_NAME }}
      TAG: ${{ github.run_number }}-${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties
      - run: chmod +x ./gradlew
      - run: ./gradlew clean build

      - uses: docker/setup-buildx-action@v3

      - name: Login to NCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.NCR_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}   # MANAGER 권한
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build & Push
        run: |
          docker build -t "$IMAGE:$TAG" -t "$IMAGE:latest" .
          docker push "$IMAGE:$TAG"
          docker push "$IMAGE:latest"
